[program:dbus]
command=dbus-daemon --system --nofork
autostart=true
autorestart=true
user=root

[program:avahi-daemon]
command=avahi-daemon --no-chroot --no-drop-root
autostart=true
autorestart=true
user=root

[program:avahi-refresh]
command=/bin/sh -c 'sleep 10; while true; do sleep 30; supervisorctl restart avahi-daemon; done'
autostart=true
autorestart=true
user=root
